[workspace]
resolver = "3"
members = ["crates/*", "apps/*", "xtask"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mcdearman/neo"

[workspace.dependencies]
neo-theme = { path = "crates/neo-theme" }
neo-render = { path = "crates/neo-render" }
armature = { path = "crates/armature" }
neo = { path = "crates/neo" }
neo-desktop = { path = "crates/neo-desktop" }
