#!/usr/bin/env python3
"""Generate crates/neo-theme/src/icons.rs from the Lucide icon-font metadata.

Usage: python3 tools/gen_icons.py
"""
import json, pathlib, re

root = pathlib.Path(__file__).resolve().parent.parent
info = json.loads((root / "crates/neo-theme/assets/lucide-info.json").read_text())

lines = [
    "//! Lucide icon set (ISC licence), rendered from the bundled icon font.",
    "//!",
    "//! Generated by `tools/gen_icons.py`. Do not edit by hand.",
    "",
    "use crate::Icon;",
    "",
]
for name in sorted(info):
    code = info[name]["encodedCode"].lstrip("\\")
    ident = re.sub(r"[^A-Za-z0-9]", "_", name).upper()
    if ident[0].isdigit():
        ident = "N" + ident
    lines.append(f'/// `{name}`')
    lines.append(f"pub const {ident}: Icon = Icon('\\u{{{code}}}');")
(root / "crates/neo-theme/src/icons.rs").write_text("\n".join(lines) + "\n")
print(f"wrote {len(info)} icons")
